#!/bin/bash
# zkfs 交互模式演示脚本

echo "=========================================="
echo "  zkfs 交互模式演示"
echo "=========================================="
echo ""
echo "启动命令:"
echo "  $ zkfs -i -s localhost:2181"
echo ""
echo "=========================================="
echo "  交互会话示例"
echo "=========================================="
echo ""
echo "✓ 已连接到 Zookeeper: localhost:2181"
echo ""
echo "交互式 Zookeeper 文件系统 (类似 telnet)"
echo "输入命令执行操作，输入'quit'或'exit'退出，输入'help'查看帮助"
echo ""
echo "zkfs> help"
echo ""
echo "可用命令:"
echo "  ls [路径]              列出子节点 (默认：/)"
echo "  dir [路径]             列出子节点及详细信息 (默认：/)"
echo "  cat <路径>             显示节点数据"
echo "  stat <路径>            显示节点状态"
echo "  rm [-r] [-f] <路径>    删除节点 (-r 递归，-f 强制)"
echo "  create <路径> [选项]   创建节点"
echo "    -d, --data <数据>     节点数据"
echo "    -f, --file <文件>     从文件读取数据"
echo "    -t, --node-type <类型>  节点类型"
echo "  set <路径> [选项]      设置节点数据"
echo "  help, h, ?             显示此帮助"
echo "  quit, exit, q          退出"
echo ""
echo "zkfs> ls /"
echo "kafka"
echo "zookeeper"
echo "config"
echo "brokers"
echo ""
echo "zkfs> dir /kafka"
echo "路径：/kafka"
echo "子节点数量：5"
echo "数据版本：1"
echo "创建时间：1705334400000"
echo "修改时间：1705334400000"
echo ""
echo "子节点列表:"
echo "  brokers (版本：2, 子节点：3, 数据大小：0 bytes)"
echo "  config (版本：0, 子节点：2, 数据大小：0 bytes)"
echo "  controller (版本：1, 子节点：0, 数据大小：256 bytes)"
echo ""
echo "zkfs> cat /kafka/controller"
echo "{\"version\":1,\"brokerid\":1,\"timestamp\":\"1705334400000\"}"
echo ""
echo "zkfs> create /config/app -d \"mysql://localhost:3306\""
echo "✓ 成功创建节点：/config/app"
echo "  写入数据：25 bytes"
echo ""
echo "zkfs> set /config/app -d \"mysql://prod-db:3306\""
echo "✓ 成功设置节点数据：/config/app"
echo "  写入数据：24 bytes"
echo ""
echo "zkfs> stat /config/app"
echo "节点路径：/config/app"
echo "创建事务 ID: 100"
echo "修改事务 ID: 150"
echo "创建时间：1705334400000"
echo "修改时间：1705334500000"
echo "数据版本：2"
echo "子节点版本：0"
echo "ACL 版本：0"
echo "临时节点所有者：0"
echo "数据长度：24 bytes"
echo "子节点数量：0"
echo "子节点修改事务 ID: 100"
echo ""
echo "zkfs> rm /config/app"
echo "✓ 成功删除：/config/app"
echo ""
echo "zkfs> quit"
echo "再见！👋"
echo ""
echo "=========================================="
echo "  演示结束"
echo "=========================================="
